apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-debug
  description: debug comp for https://github.com/backstage/backstage/issues/26908
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
